services:
  app:
    image: golang:1.24.0-bullseye
    container_name: go-api
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c '
      go install github.com/air-verse/air@latest
      && air --build.cmd "go build -o tmp/api main.go" --build.bin "./tmp/api"
      '
